"use client";
import { useEffect, useRef, useState } from 'react';
import { OscilloscopeSimulator } from '../lib/simulator';

/**
 * OscilloscopeDisplay Component
 * 
 * Responsible for rendering the high-performance HTML5 Canvas grid and waveform traces.
 * Evaluates the serial data payloads generated by the simulator and plots them to screen.
 */
export default function OscilloscopeDisplay({ isRunning, frequency, amplitude, waveType, message }) {
  const canvasRef = useRef(null);

  // dataRef stores the history of our ADC readings to draw across the X-axis
  const dataRef = useRef([]);
  const simulatorRef = useRef(null);
  const serialBufferRef = useRef(''); // Helps us reconstruct broken simulated UART chunks
  const renderFrameRef = useRef(null);
  const paramsRef = useRef({ frequency, amplitude, waveType, message });
  const timeRef = useRef(0);

  const [metrics, setMetrics] = useState({ vpp: 0, freq: 0 });

  // 1. Sync React Props to the mutable Simulator state
  useEffect(() => {
    paramsRef.current = { frequency, amplitude, waveType, message };
    if (simulatorRef.current) {
      simulatorRef.current.setParameters(paramsRef.current);
    }
    // Wipe the screen clean when settings change to prevent visual artifacting
    dataRef.current = [];
  }, [frequency, amplitude, waveType, message]);

  // 2. Main lifecycle hook for the Simulator and Render Loop
  useEffect(() => {
    // Instantiate the "hardware" microcontroller simulator
    simulatorRef.current = new OscilloscopeSimulator({
      sampleRate: 2000, // Processing 2000 discrete math points every second
      onSerialData: (chunk) => {
        // --- Virtual Serial Buffer Parser ---
        // Simulates receiving raw strings over a hardware serial port (e.g. from an Arduino UART)
        serialBufferRef.current += chunk;
        const lines = serialBufferRef.current.split('\n');

        // The last line might be partially downloaded, keep it in the buffer until a newline arrives
        serialBufferRef.current = lines.pop();

        for (const line of lines) {
          const val = line.trim();
          if (val !== '') {
            // Parse multi-channel data (e.g., "512,1023,0") into an array of integers
            const channelValues = val.split(',').map(v => parseInt(v, 10));
            // Push values directly into array for drawing
            dataRef.current.push(channelValues);

            // Limit buffer to 4000 items to prevent running out of system memory
            if (dataRef.current.length > 4000) {
              dataRef.current.shift();
            }
          }
        }
      }
    });

    simulatorRef.current.setParameters(paramsRef.current);

    // --- High-Performance Draw Loop ---
    let lastTime = performance.now();
    const render = (time) => {
      // Calculate how many milliseconds have actually passed since the last draw frame
      if (simulatorRef.current && simulatorRef.current.isRunning) {
        const deltaMs = time - lastTime;

        // Using our sampleRate (2000), calculate exactly how many samples need to be computed
        // to catch up to the real-world passage of elapsed time on the monitor. 
        // Example: 16ms of time passed = require ~32 new points simulated.
        const samples = Math.floor(deltaMs * (simulatorRef.current.sampleRate / 1000));
        if (samples > 0) {
          simulatorRef.current.advance(samples); // Push the physics engine forward
          lastTime = time;
        }
      } else {
        lastTime = time;
      }

      drawCanvas(); // Paint all points onto HTML5 Canvas

      // Request next frame from browser at 60 FPS
      renderFrameRef.current = requestAnimationFrame(render);
    };

    // Kickstart the engine
    lastTime = performance.now();
    renderFrameRef.current = requestAnimationFrame(render);

    // React cleanup to prevent memory leaks when navigating away
    return () => {
      cancelAnimationFrame(renderFrameRef.current);
      if (simulatorRef.current) {
        simulatorRef.current.pause();
      }
    };
  }, []);

  // 3. Play/Pause toggle interceptor
  useEffect(() => {
    if (simulatorRef.current) {
      if (isRunning) simulatorRef.current.start();
      else simulatorRef.current.pause();
    }
  }, [isRunning]);

  /**
   * The actual mapping logic to draw ADC signals visually on UI.
   */
  const drawCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d', { alpha: false });
    const width = canvas.width;
    const height = canvas.height;

    // Fill stark black screen background
    ctx.fillStyle = '#000000';
    ctx.fillRect(0, 0, width, height);

    // Draw the aesthetic crosshairs and grids
    drawGrid(ctx, width, height);

    const data = dataRef.current;
    if (data.length === 0) return;

    // We only display the latest 4000 items (representing exactly 2.0 seconds at 2000Hz)
    // Adjusting this acts exactly like twisting the "Time Base" (seconds/div) knob on a real scope.
    const displayWindowSamples = 4000;
    const startIndex = Math.max(0, data.length - displayWindowSamples);
    const visibleData = data.slice(startIndex);

    if (visibleData.length === 0) return;

    // Determine how many signals (traces) are actively being sent to us (1 for Sine, 3 for SPI, etc)
    const numChannels = visibleData[0].length;
    const margin = 20;

    // Draw lines separately for each active channel
    for (let c = 0; c < numChannels; c++) {
      ctx.beginPath();

      // Styling logic: Give channels different stroke styles so they can be identified
      if (c === 0) { ctx.strokeStyle = '#ffffff'; ctx.lineWidth = 2; }
      else if (c === 1) { ctx.strokeStyle = '#cccccc'; ctx.lineWidth = 2; ctx.setLineDash([4, 2]); }
      else { ctx.strokeStyle = '#888888'; ctx.lineWidth = 2; ctx.setLineDash([1, 2]); }

      // Layout logic: Stack multi-channel traces vertically (like a Logic Analyzer)
      const drawableHeight = (height - margin * 2) / numChannels;
      const channelOffsetY = margin + (c * drawableHeight);
      const traceHeight = drawableHeight * 0.8;
      const traceOffsetTop = channelOffsetY + (drawableHeight * 0.1);

      // Connect the dots!
      for (let i = 0; i < visibleData.length; i++) {
        const adcValue = visibleData[i][c];

        // Reverse-evaluate the 10-bit integer (1023 max) back to a normalized ratio (0.0 to 1.0)
        const normalizedY = adcValue / 1023;

        // Map data sequence index to X-pixel coordinates 
        const x = (i / displayWindowSamples) * width;

        // Map hardware ratio to Y-pixel coordinates, inverted because Y=0 is canvas top
        const y = traceOffsetTop + traceHeight - (normalizedY * traceHeight);

        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.stroke();
      ctx.setLineDash([]); // Reset dash config globally
    }

    // Performance protection: Update text UI metrics only once every ~30 frames
    timeRef.current++;
    if (timeRef.current % 30 === 0 && visibleData.length > 10) {
      calculateMetrics(visibleData, numChannels);
    }
  };

  const drawGrid = (ctx, width, height) => {
    ctx.strokeStyle = '#333333';
    ctx.lineWidth = 1;
    ctx.setLineDash([2, 4]); // Creates dotted line
    ctx.beginPath();

    // Draw horizontal voltage divisions
    for (let i = 0; i <= 10; i++) {
      const y = (i / 10) * height;
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
    }

    // Draw vertical time divisions
    for (let i = 0; i <= 10; i++) {
      const x = (i / 10) * width;
      ctx.moveTo(x, 0);
      ctx.lineTo(x, height);
    }

    ctx.stroke();
    ctx.setLineDash([]);
    ctx.strokeStyle = '#555555';

    // Solid bold center crosshairs
    ctx.beginPath();
    ctx.moveTo(0, height / 2);
    ctx.lineTo(width, height / 2);
    ctx.moveTo(width / 2, 0);
    ctx.lineTo(width / 2, height);
    ctx.stroke();
  };

  const calculateMetrics = (data, numChannels) => {
    // Math to evaluate peak-to-peak voltage of Channel 1
    let minAdc = 1023;
    let maxAdc = 0;
    for (const valArr of data) {
      const val = valArr[0];
      if (val < minAdc) minAdc = val;
      if (val > maxAdc) maxAdc = val;
    }

    // Map back relative 0-1023 ADC bounds to absolute 0-5.0 limits
    const maxV = (maxAdc / 1023) * 5;
    const minV = (minAdc / 1023) * 5;
    const vpp = (maxV - minV).toFixed(2);

    setMetrics({
      vpp,
      freq: frequency.toFixed(1),
      channels: numChannels
    });
  };

  // Switch tag identities to signify pin labels depending on active logic
  const getChannelLabels = () => {
    if (waveType === 'i2c') return 'CH1:SCL CH2:SDA';
    if (waveType === 'spi') return 'CH1:SCK CH2:MOSI CH3:CS';
    if (waveType === 'uart') return 'CH1:TX (UART)';
    return 'CH1-AC';
  };

  return (
    <div style={containerStyle}>
      <div style={screenContainerStyle}>
        <canvas
          ref={canvasRef}
          width={800}
          height={400}
          style={canvasStyle}
        />
        <div style={overlayStyle}>
          <div style={metricStyle}>VPP: {metrics.vpp}V</div>
          <div style={metricStyle}>FREQ: {metrics.freq}HZ</div>
          <div style={metricStyle}>{getChannelLabels()}</div>
        </div>
      </div>
    </div>
  );
}

const containerStyle = {
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  padding: '1rem',
  background: '#000000',
  border: '2px solid #ffffff',
  margin: '1rem',
};

const screenContainerStyle = {
  position: 'relative',
  border: '2px solid #ffffff',
  backgroundColor: '#000000',
  overflow: 'hidden',
};

const canvasStyle = {
  display: 'block',
  width: '100%',
  maxWidth: '800px',
  height: 'auto',
  aspectRatio: '2 / 1',
  imageRendering: 'pixelated',
};

const overlayStyle = {
  position: 'absolute',
  top: '0',
  left: '0',
  right: '0',
  display: 'flex',
  justifyContent: 'space-between',
  pointerEvents: 'none',
  padding: '8px',
};

const metricStyle = {
  fontFamily: 'monospace',
  fontSize: '16px',
  color: '#ffffff',
  background: '#000000',
  padding: '2px 6px',
  border: '1px solid #ffffff',
};
